### ISSUE TITLE
Attempting to read from a non-existent database can create many distinct client IDs in the session metrics

### ISSUE THREAD

**Issue by sebright** [googleapis/java-spanner#202] opened 2020-05-13 09:00 UTC
I noticed that calling `Spanner.getDatabaseClient` with a non-existent database and then trying to read from the database can cause new client IDs to appear in the OpenCensus session metrics.  The client IDs for the non-existent database seem problematic because they can cause the size of the metrics to grow.

Here is a simplified reproduction:

google-cloud-spanner version: 1.54.0
opencensus-java version: 0.26.0

```java
import com.google.cloud.spanner.DatabaseId;
import com.google.cloud.spanner.InstanceConfigId;
import com.google.cloud.spanner.InstanceId;
import com.google.cloud.spanner.InstanceInfo;
import com.google.cloud.spanner.Key;
import com.google.cloud.spanner.Spanner;
import com.google.cloud.spanner.SpannerOptions;
import io.opencensus.exporter.stats.stackdriver.StackdriverStatsExporter;
import java.util.Arrays;
import org.junit.Test;

public class ClientIdTest {
  @Test
  public void testClientId() throws Exception {
    StackdriverStatsExporter.createAndRegister();
    Spanner spanner = SpannerOptions.getDefaultInstance().getService();
    String projectId = spanner.getOptions().getProjectId();
    InstanceId instanceId = InstanceId.of(projectId, "my-instance");
    InstanceConfigId instanceConfigId = InstanceConfigId.of(projectId, "regional-us-central1");
    spanner
        .getInstanceAdminClient()
        .createInstance(
            InstanceInfo.newBuilder(instanceId)
                .setInstanceConfigId(instanceConfigId)
                .setDisplayName("my-instance")
                .setNodeCount(1)
                .build())
        .get();
    DatabaseId databaseId = DatabaseId.of(instanceId, "my-database");

    for (int i = 0; i < 100; i++) {
      try {
        spanner
            .getDatabaseClient(databaseId)
            .singleUse()
            .readRow("MyTable", Key.of(0), Arrays.asList("MyColumn"));
      } catch (Exception e) {
        // ignore
      }
    }
    Thread.sleep(300_000);
  }
}
```

The metrics exported to Stackdriver contain 100 client IDs.  For example, here is `in_use_sessions`:

![session-metrics](https://user-images.githubusercontent.com/19807615/81789900-7d48b900-94b9-11ea-8bdf-e29d977be1cc.png)

![session-metrics-2](https://user-images.githubusercontent.com/19807615/81792755-542a2780-94bd-11ea-810d-fec1a8200005.png)

**Comment by sebright** [comment] 2020-05-15 06:47
I tried updating to master after #206 was merged, but I'm still getting a large number of client IDs.  I also tried running the reproduction above, but this time the client IDs ranged from 1 to 50 instead of 1 to 100.

**Comment by olavloite** [comment] 2020-05-15 07:52
@sebright 
I'm not really able to reproduce this locally. I've just added an [additional test case](https://github.com/googleapis/java-spanner/blob/41d960f3039c4e8621b027e7feb0d9e49b4e5f4e/google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java#L933) based on your reproduction code above, but I'm seeing the same client id each time.

The client ids in the range 1 to 50 especially baffles me. Is your test code literally equal to the reproduction code you mentioned above, or could it be that the test code is somehow running parts of it in parallel?

**Comment by olavloite** [comment] 2020-07-10 16:37
@sebright Friendly ping. Is this still an issue?

**Comment by sebright** [comment] 2020-07-14 20:09
@olavloite Sorry for the delay.  I tried running the reproduction from the first comment again with google-cloud-spanner 1.58.0.  This time I didn't see any stats recorded for the metric in_use_sessions, but I saw the same behavior as in https://github.com/googleapis/java-spanner/issues/202#issuecomment-629061813 for max_in_use_sessions.  There were 50 distinct client IDs (client-1 through client-50).

**Comment by olavloite** [comment] 2020-07-16 11:20
@sebright I'm still not able to reproduce this locally using both a real Cloud Spanner instance as well as a local mock server. I've therefore created a small integration test so we can use that to try to figure out where the difference is coming from. The [integration test](https://github.com/googleapis/java-spanner/pull/353/files#diff-87511c6d56a15c1704dc880834285c19) in #353 is based on the example at the beginning of this issue and checks that only one client id is created, and it currently succeeds.

Note that:
1. The integration test itself does not create a new instance, but uses the instance that is created for the integration test run. That should however as far as I can see make any difference for this case.
1. All the read operations will fail as the database that is requested does not exist. Those errors are ignored.

At the end of the test it verifies that only one client id has been generated and used. Would you mind having a look and see if you can spot where the difference in outcome could be coming from in this test case, compared to the test that you run on your setup?
The outcome of the test run can be found here: https://source.cloud.google.com/results/invocations/03df0d70-cdef-41aa-ab8b-5208de7e6959/targets/github%2Fjava-spanner%2Fgoogle-cloud-spanner%2Ftarget%2Ffailsafe-reports%2Fintegration%2Fcom.google.cloud.spanner.it.ITClientIdTest/tests

**Comment by skuruppu** [comment] 2020-09-16 01:34
Friendly ping @sebright. If you could look at the code that @olavloite wrote, it would help us to repro the issue.

**Comment by skuruppu** [comment] 2020-10-13 00:43
Since we haven't had updates here in a while, I'm going to close the issue. Please re-open if this issue is still happening.

**Comment by sebright** [comment] 2020-12-29 07:22
Thanks for sharing the integration test.  I rebased #353 and tried running it, and I think I understand the difference.  My reproduction uses opencensus 0.26.0 and has a dependency on opencensus-impl, and the integration test uses opencensus 0.24.0 without opencensus-impl.  The integration test fails when I add these dependencies to `google-cloud-spanner/pom.xml`:

```
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-api</artifactId>
      <version>0.26.0</version>
    </dependency>
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-contrib-grpc-util</artifactId>
      <version>0.26.0</version>
    </dependency>
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-impl-core</artifactId>
      <version>0.26.0</version>
    </dependency>
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-impl</artifactId>
      <version>0.26.0</version>
    </dependency>
```

It looks like opencensus-impl 0.26.0 throws an exception when multiple time series are recorded with the same client ID.  The test alternates between throwing "Database not found" and "A different time series with the same labels already exists" exceptions in each iteration of the for loop.  Here is the stack trace for the time series error:

```
java.lang.IllegalArgumentException: A different time series with the same labels already exists.
	at io.opencensus.implcore.metrics.DerivedLongGaugeImpl.createTimeSeries(DerivedLongGaugeImpl.java:91)
	at com.google.cloud.spanner.SessionPool.initMetricsCollection(SessionPool.java:2381)
	at com.google.cloud.spanner.SessionPool.<init>(SessionPool.java:1862)
	at com.google.cloud.spanner.SessionPool.createPool(SessionPool.java:1839)
	at com.google.cloud.spanner.SessionPool.createPool(SessionPool.java:1798)
	at com.google.cloud.spanner.SpannerImpl.getDatabaseClient(SpannerImpl.java:225)
	at com.google.cloud.spanner.it.ITClientIdTest.testClientId(ITClientIdTest.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

**Comment by olavloite** [comment] 2020-12-31 10:19
@sebright Thanks for the reproduction case! I'm able to reproduce and solve it for version 0.26 now.

See the linked PR for more information, but the TLDR is that OpenCensusImpl 0.24 does not allow the same metric to be registered multiple times, which means that it is not solvable for that version. 0.26 does work as expected with the change in #766.

**Closed** 2021-01-14 22:19 UTC
Labels: :rotating_light:, api: spanner, priority: p2, type: bug
