### ISSUE TITLE
Spanner: BatchReadOnlyTransaction closes shared sessions on close()

### ISSUE THREAD

**Issue by nielm** [googleapis/java-spanner#1651] opened 2022-01-18 08:50 UTC
[class `BatchReadOnlyTransactionImpl`](https://github.com/googleapis/java-spanner/blob/ae222be1e1689a15e4994a08e9cb8731f404b4a8/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClientImpl.java#L77) is an AutoClosable (via `MultiUseReadOnlyTransaction->AbstractReadContext->ReadContext->AutoClosable`)

The [`close()`](https://github.com/googleapis/java-spanner/blob/ae222be1e1689a15e4994a08e9cb8731f404b4a8/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClientImpl.java#L218) method always closes both the session and the transaction. 

This is fine if a session has been created for this transaction, using [`batchReadOnlyTransaction(TimestampBound)`](https://github.com/googleapis/java-spanner/blob/ae222be1e1689a15e4994a08e9cb8731f404b4a8/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClientImpl.java#L46)

But a BatchReadOnlyTransaction can also be created from an existing shared BatchTransaction: [`batchReadOnlyTransaction(BatchTransactionId)`](https://github.com/googleapis/java-spanner/blob/ae222be1e1689a15e4994a08e9cb8731f404b4a8/google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClientImpl.java#L61). \
In this case, the Session is not _created_ for this transaction, but is taken from the `SessionID` from the `BatchTransactionId`, and so it is a _shared session_ so should not be closed when this transaction is closed.

Therefore the `close()` method should be fixed to _only_ close the session when the session has been created for this transaction. 

#### Environment details

2. OS type and version: all
3. Java version: all 
4.  version(s): latest (6.17.4)

#### Steps to reproduce

  1. Use the sample code at https://cloud.google.com/spanner/docs/samples/spanner-batch-client#spanner_batch_client-java
  2. Modify the code so that each thread creates a new separate batchReadOnlyTransaction, and uses that to perform the read (so that a different channel is used for the read)
      ```
      try (BatchReadOnlyTransaction readTxn = batchClient.batchReadOnlyTransaction(txn.getBatchTransactionId())) {
         try (ResultSet results = readTxn.execute(p)) {
            while (results.next()) {
            ...
            }
         }
      }
      ...
      ```
  3. Run the code on a large enough table to get a reasonably partitioned transaction in a single process
  4. Watch the code fail as one thread uses a session that has been closed by another

**Comment by rajatbhatta** [comment] 2022-02-01 10:36
I took a look at the issue, and I acknowledge the same. I've started working on reproducing the issue. Will update here, based on my future progress.

**Comment by ansh0l** [comment] 2022-02-15 07:46
Keeping the ticket open since we expect the change to ship out a little later batched with few other changes. But otherwise, the changes for these are done as referenced in the PR by @rajatbhatta

**Comment by rajatbhatta** [comment] 2022-02-17 06:54
Closing the issue as the changes have been released, thanks!

**Closed by rajatbhatta** 2022-02-17 06:54 UTC
Labels: priority: p2, api: spanner
