### ISSUE TITLE
Check for NonNull while getting value from a Nullable String Column.

### ISSUE THREAD

**Issue by natashasehgal** [googleapis/java-spanner#1902] opened 2022-05-29 19:16 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/java-spanner/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types:  Spanner  > Java Client
2. OS type and version: macOS Monterey version 12.3.1
3. Java version: openjdk version "11.0.14" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu11.54+23-CA (build 11.0.14+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.54+23-CA (build 11.0.14+9-LTS, mixed mode)
4.  version(s): 'com.google.cloud:google-cloud-spanner:6.18.0' but  issue also in latest 6.25x version.

#### Steps to reproduce

  1. Create a table "table" with nullable string column "abc"
  2. Insert a row with null value in "abc" column.
  3. Attempt to read this value from a Java Client

#### Code example

```java
        while (resultSet.next()) {
            Struct struct = resultSet.getCurrentRowAsStruct();
            String abcValue = struct.getString("abc")

```

#### Stack trace
```
Error Message/Stacktrace/Screenshot If Applicable: 
Trying to read data from "table" table by using struct getString() -
! java.lang.NullPointerException: Column abc contains NULL value
! at com.google.cloud.spanner.AbstractStructReader.checkNonNull(AbstractStructReader.java:431)
! at com.google.cloud.spanner.AbstractStructReader.checkNonNullOfTypes(AbstractStructReader.java:458)
! at com.google.cloud.spanner.AbstractStructReader.getString(AbstractStructReader.java:174)
```

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by rajatbhatta** [comment] 2022-05-31 07:49
We have a non-null check in getString(String columnName) method, and we raise a NullPointerException if the column value is null, by design.

You could handle the null column value case separately as follows:
```
while (resultSet.next()) {
    Struct struct = resultSet.getCurrentRowAsStruct();
    if (struct.isNull("abc")) {
        // handle null column value case.
    } else {
        String abcValue = struct.getString("abc");
    }
}
```

**Comment by rajatbhatta** [comment] 2022-06-02 12:44
Closing this issue based on https://github.com/googleapis/java-spanner/issues/1902#issuecomment-1141785583. Feel free to re-open if needed.

**Closed by rajatbhatta** 2022-06-02 12:44 UTC
Labels: type: question, api: spanner
